# Generated by Django 4.2.7 on 2023-11-28 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0008_remove_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='storeapp.Enrollment', to='storeapp.product'),
        ),
    ]
