# Generated by Django 4.2.7 on 2023-11-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0009_enrollment_order_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='OrderProduct',
        ),
    ]
