# Generated by Django 4.2.7 on 2023-12-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0015_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='storeapp_orderproduct', to='storeapp.product'),
        ),
    ]
