# Generated by Django 4.2.7 on 2023-12-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0017_alter_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='storeapp.product'),
        ),
    ]
