# Generated by Django 4.2.7 on 2023-12-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0020_alter_order_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='storapp_orderproduct',
        ),
    ]
