# Generated by Django 4.2.7 on 2023-12-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0022_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(db_table='storeapp_orderproduct', to='storeapp.product'),
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
