# Generated by Django 4.2.7 on 2023-12-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0023_alter_order_products_alter_order_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
