# Generated by Django 4.2.7 on 2023-12-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0025_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
