# Generated by Django 4.2.7 on 2023-12-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0029_remove_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.DateField(auto_now_add=True, default=12),
            preserve_default=False,
        ),
    ]
